[package]
name = "happy-server-bot"
version = "0.1.0"
authors = ["curlicue <>"]
edition = "2018"

[dependencies]
serenity = "0.5"
#log = "0.4.6"
env_logger = "0.6.0"
toml = "0.4.10"
serde = "1.0"
serde_derive = "1.0"
reqwest = "0.9.15"
Inflector = "0.11.4"
